name: test
on: [push]
jobs:
  pytest:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dev tools
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pytest
